# Generated by Django 2.0.2 on 2024-09-12 21:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltaje', models.FloatField()),
                ('corriente', models.FloatField()),
                ('resistencia', models.FloatField()),
                ('campo', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Medición',
                'verbose_name_plural': 'Mediciones',
                'ordering': ['corriente'],
            },
        ),
        migrations.CreateModel(
            name='Perfil_Parametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_parametro_name', models.CharField(max_length=100)),
                ('intervalo_simetrico', models.FloatField(validators=[django.core.validators.MinValueValidator(-1.05), django.core.validators.MaxValueValidator(1.05)])),
                ('intervalo_corriente', models.IntegerField()),
                ('delay', models.FloatField(validators=[django.core.validators.MinValueValidator(0.001), django.core.validators.MaxValueValidator(999.999)])),
                ('perfil_parametro_state', models.CharField(blank=True, default='t', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Perfil Parametro',
                'verbose_name_plural': 'Perfil Parametros',
                'ordering': ['perfil_parametro_name'],
            },
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prueba_name', models.CharField(blank=True, max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('grafico', models.ImageField(blank=True, null=True, upload_to='')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('prueba_state', models.CharField(default='t', max_length=10)),
                ('id_perfil_parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caracterizacion.Perfil_Parametro')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prueba',
                'verbose_name_plural': 'Pruebas',
                'ordering': ['prueba_name'],
            },
        ),
        migrations.AddField(
            model_name='medicion',
            name='id_prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caracterizacion.Prueba'),
        ),
    ]
