# Generated by Django 2.0.2 on 2024-10-10 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caracterizacion', '0003_auto_20241004_1835'),
        ('caracterizacion', '0003_auto_20241004_2141'),
    ]

    operations = [
    ]
