# Generated by Django 2.0.2 on 2024-11-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracterizacion', '0004_merge_20241010_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='delta_v',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='saturacion_campo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil_parametro',
            name='fija_corriente',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='configuracion_rele',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='intercepto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='pendiente',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
